# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'vcr'
require File.join(File.dirname(__FILE__), '..', 'lib', 'page')
require File.join(File.dirname(__FILE__), '..', 'lib', 'frequency')
require File.join(File.dirname(__FILE__), '..', 'lib', 'classifier')
require File.join(File.dirname(__FILE__), '..', 'lib', 'techdata')

RSpec.configure do |config|
  config.extend VCR::RSpec::Macros
end

VCR.configure do |c|
  c.cassette_library_dir     = 'spec/cassettes'
  c.hook_into                :webmock
  c.default_cassette_options = { :record => :new_episodes }
end
